Feat: reset password
unicsmcr/unics_social_api pull request #103
Opened 2020-09-19 13:49 UTC by sabuqamar

Resolves #17 

Added a forgot password and reset password routes for both users who forgot their password and users who want to change their password. An email is sent with a PasswordReset JWT. This feature can only be accessed by verified users.

2020-09-19 17:02 UTC, amishshah requested changes

2020-09-19 17:02 UTC, amishshah commented on src/controllers/UserController.ts
> +import { VerifyEmailTemplate, PassowrdEmailTemplate, ReportEmailTemplate } from '../util/emails';
```suggestion
import { VerifyEmailTemplate, PasswordEmailTemplate, ReportEmailTemplate } from '../util/emails';
```

Just a typo here!

2020-09-19 17:02 UTC, amishshah commented on src/controllers/UserController.ts
> +			const user = await this.userService.forgotPassword(req.body);
I think that the `forgotPassword` method in the User Service is redundant. From what I can tell, it does these 2 things:

1) Finds a user's account from their email address
2) Makes sure that their account is not unverified.

I think that the second point isn't really needed - I think that users should be able to reset their password even if they haven't verified their account yet, however if you have an explanation for this then please let me know!

In that case, it may just be easier to use the existing `findOne` method in User Service to find a user by their email, or create a method that does this specific task.

2020-09-19 17:02 UTC, amishshah commented on src/routes/UserRoutes.ts
> +		router.post('/forgot_password', getUser(TokenType.Auth), this.userController.forgotPassword.bind(this.userController));
```suggestion
		router.post('/forgot_password', this.userController.forgotPassword.bind(this.userController));
```

Users may not be able to login, so we can't require that they have a valid authorization token. The only thing we can do is take the user's email address.

2020-09-19 17:02 UTC, amishshah commented on src/services/UserService.ts
> +	public async forgotPassword(userEmail: string): Promise<APIPrivateUser> {
See above, I think this method may be redundant.

2020-09-19 17:02 UTC, amishshah commented on src/services/UserService.ts
> +export interface PasswordResetDataToCreate { password: string }
```suggestion
export interface PasswordResetData { password: string }
```

I think the `ToCreate` for this specific type can be confusing, it exists for the other ones as they define the required data needed to create an entity (e.g. to create a user, to create a profile). Since the password isn't an entity in itself, I think it is safe to omit this.

2020-09-19 17:02 UTC, amishshah commented on src/services/UserService.ts
> +			if (!data.password) {
This check could be moved to the top of the block to avoid unnecessarily fetching the user only to find that their request was invalid.

2020-09-19 17:02 UTC, amishshah commented on src/util/auth.ts
> +export const CombinedEnum = TokenType.Auth | TokenType.PasswordReset;
I don't think is required anymore!

```suggestion
```

2020-09-19 17:07 UTC, amishshah commented
Looks great mostly @sabuqamar! Just wanted to ask the reasoning behind only verified users being able to reset their password?

2020-09-19 17:44 UTC, sabuqamar commented on src/controllers/UserController.ts
> +			const user = await this.userService.forgotPassword(req.body);
So for the case of someone trying to reset their password before verifying their account, they might try logging in and confuse not verifying their account with forgetting their password. Also, they will have to verify their email to access their account anyways. However, if you think it is an unnecessary condition I can remove it.

2020-09-19 22:31 UTC, amishshah commented on src/controllers/UserController.ts
> +			const user = await this.userService.forgotPassword(req.body);
Ahh ok, that's fine then! You can keep it included.

2020-09-24 09:32 UTC, amishshah approved these changes

2020-09-24 09:36 UTC, merged