fix: added check for unverified users trying to authenticate
unicsmcr/unics_social_api pull request #112
Opened 2020-09-25 02:55 UTC by HishamYahya

Closes #106

2020-09-25 09:34 UTC, amishshah requested changes
Code looks good! But can you try and investigate why the tests are failing and fix the issues @HishamYahya?

2020-09-26 10:03 UTC, HishamYahya commented
One of the tests is testing if it always successfully authenticates when the correct credentials are given. Should I move the checking somewhere else or modify the test to account for unverified user authentication? @amishshah

2020-09-26 12:49 UTC, amishshah commented
> One of the tests is testing if it always successfully authenticates when the correct credentials are given. Should I move the checking somewhere else or modify the test to account for unverified user authentication? @amishshah

Can you modify the test to use a test user that is verified?

2020-09-26 15:21 UTC, amishshah approved these changes

2020-09-26 15:21 UTC, merged